### ISSUE TITLE
Update node-sass to work with node 15

### ISSUE THREAD

**Issue by haynesgt** [jamesseanwright/term4all#3]
Building with docker image node:15 gives a bunch of compilation errors when running with `npm install`

`../src/create_string.cpp:17:37: error: no matching function for call to 'v8::String::Utf8Value::Utf8Value`

Fix with

```diff --git a/package.json b/package.json
index 6256ec8..7320225 100644
--- a/package.json
+++ b/package.json
@@ -32,7 +32,7 @@
     "electron-prebuilt": "1.2.5",
     "jsdom": "9.4.1",
     "mocha": "2.5.3",
-    "node-sass": "3.8.0",
+    "node-sass": "4.12.0",
     "sinon": "1.17.4"
   },
   "dependencies": {
```

**Comment by jamesseanwright** [comment]
Hey @haynesgt!

Thanks for highlighting this issue, but I'm no longer maintain this repo; I'll archive it accordingly.

Do feel free to fork and continue its development if you'd like.
